# Generated by Django 5.0.1 on 2024-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("carbs", models.FloatField()),
                ("protein", models.FloatField()),
                ("fats", models.FloatField()),
                ("calories", models.IntegerField()),
            ],
        ),
    ]
